### ISSUE TITLE
The process cannot access the file 'xyz\Machine.Specifications.VSRunner.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by jonathh21** [machine-visualstudio/machine.vstestadapter#43]
Hi,

One of my colleagues is quite consistently seeing the error as below:

Error: Machine Specifications Visual Studio Test Adapter - Error while executing specifications in assembly xyz.dll - The process cannot access the file 'xyz\Machine.Specifications.VSRunner.dll' because it is being used by another process.

I can't recreate it, but I suspect it relates to the fact that the test adapter is dynamically creating and deleting an aggregated file 

                    string path = Path.Combine(baseDirectory, runnerDllName);
                    if (File.Exists(path))
                    {
                        File.Delete(path);
                    }

I am not really sure why it has to create/delete a file with each run it doesn't sound sensible.. but it might need a guid or something in there too?

**Comment by ivanz** [comment]
Are you running the tests in parallel?

**Comment by jonathh21** [comment]
The short answer to that is 'Yes'

The longer answer is that we are running using a test configuration testing
of '<MaxCpuCount>4</MaxCpuCount>' which ought to make it run in parrallel.
However I have never confirmed this, nor is anyone else in the team getting
this.

I am not sure why it needs to create and then delete the file, but perhaps
it needs to use Path.GetRandomFileName/Path.GetTempFileName or a guid in
the path, with a suitable locking section?

**Comment by jonathh21** [comment]
I have made a temporary fix to this such that the executor now has an 'out'
parameter that is the name of the destination vsrunner file, which is
generated with a guid in the file name. This is then deleted.

However, I toyed with the idea of just checking if the vsrunner is present,
and copying if it isn't and never deleting it. Saves a few cycles on
creating a deleting the file. I didn't look at how it, itself would hand
concurrency.

**Comment by ivanz** [comment]
I am working on a new version of the adapter with new discovery and updated execution engine. I think some of the changes I made will resolve what you are seeing. I am hoping to release an early beta build shortly.

**Comment by ivanz** [comment]
@jonathh21 2.0.0-beta1 is out now: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v2.0.0-beta1 

Let me know how it works for you and raise any issues

**Comment by jonathh21** [comment]
Awesome! thanks.. I'll try it now.

**Comment by jonathh21** [comment]
Unfortunately my very first test resulted in that vsrunner exception due to
concurrency :(

I'll do some more testing tho.

**Comment by ivanz** [comment]
Do you have a stacktrace?

**Comment by ivanz** [comment]
I think the issue is (in this method)[https://github.com/machine-visualstudio/machine.vstestadapter/blob/master/Source/Machine.VSTestAdapter/Helpers/IsolatedAppDomainExecutionScope.cs#L53] . I am guessing File.Copy is locking the source file potentially...

**Comment by ivanz** [comment]
@jonathh21 I have changed the way copy is done. Can you please test this CI build: https://ci.appveyor.com/project/machine-visualstudio/machine-vstestadapter/build/2.0.0-beta1+49/artifacts

**Comment by jonathh21** [comment]
It is not looking good I am afriad. 

I have only had time to dump the new files over my existing ones, and I am still getting an exception.

The difference now is it is in a different file..

> 
The process cannot access the file 'C:\WSc1\Development\Core\bin\debug\Machine.TestAdapter.dll' because it is being used by another process.

I don't have time right now to investigate in detail (sorrY), but instinctively there could be a race condition.. Is it not possible to copy to a unique file, and have each thread use a different version then delete? I did experiment with this yesterday but I couldn't get the assembly to load..

**Comment by ivanz** [comment]
It is copying to a unique folder. The problem here is that the source file to copy locked by something. I have an idea how to fix that, which is to move the runner to a separate all, which is not loaded in the current domain. I will have a play  tonight/tomorrow, by expect it to be a bit tricky. I need to find a way to repro this locally as well.

**Comment by ivanz** [comment]
I am unable to reproduce it locally:

```
c:\code\VSOBuildTesting>vstest.console .\ClassLibrary.MoreTests\bin\Debug\ClassLibrary.MoreTests.dll .\VSOBuildTesting.ClassLibrary.Tests\bin\Debug\ClassLibrary.Tests.dll /testadapterpath:.\packages /Settings:test.runsettings
Microsoft (R) Test Execution Command Line Tool Version 14.0.24720.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Information: Machine Specifications Visual Studio Test Adapter - Executing tests in c:\code\VSOBuildTesting\VSOBuildTesting.ClassLibrary.Tests\bin\Debug\ClassLibrary.Tests.dll

Information: Machine Specifications Visual Studio Test Adapter - Executing tests in c:\code\VSOBuildTesting\ClassLibrary.MoreTests\bin\Debug\ClassLibrary.MoreTests.dll
```

with `test.runsettings`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <MaxCpuCount>4</MaxCpuCount>
  </RunConfiguration>
</RunSettings>
```

**Comment by ivanz** [comment]
Oh okay. Managed to reproduce if I put all test assemblies in the same folder. The fix may be simpler than I thought :)

**Comment by ivanz** [comment]
@jonathh21: Fix is live in Beta 2. You can grab the binaries from CI here: https://ci.appveyor.com/project/machine-visualstudio/machine-vstestadapter/build/2.0.0-beta2+54

**Comment by jonathh21** [comment]
What about deleting the file???

**Comment by ivanz** [comment]
@jonathh21 The current code doesn't delete any files other than the shadow copy assembly cache in C:\windows\temp so you should be fine. I will have a think if there is a way to clean-up those assemblies, but in your scenario (multiple test files in same folder) it will be non-trivial if impossible, because the vstest.console is spinning up multiple processes  of the mspec adaptor. I will have a look at what the xunit and nunit do about this.

**Comment by jonathh21** [comment]
Ivan,

The latest looks good! myself and one other colleague have tested this
morning, and am now preparing to roll it out to the team as a whole.

Thank you so much for your help!

**Comment by ivanz** [comment]
Great. Let me know how it goes and if you hit any issues. I want to add one more feature for 2.0.0, which is to output test results like this `When something - it should succeed` rather than `it should succeed` when ran in CI, so that it's easier to read failures. I will probably add this as an optional flag on the command line

**Comment by ivanz** [comment]
Unfortunately I have to re-open this issue, because not replacing the TestAdaptor.dll with a new one is causing other issues. I will shortly create a pull request with an alternative approach to avoid cross-process race conditions. However copying files into the test assembly folder feels dirty, so whenever I get a chance I will see if maybe we can copy stuff into a temporary folder and run from there..
